image:
  name: atlassian/default-image:4

pipelines:
  default:
    - step:
        name: 'Test pipe'
        oidc: true
        script:
          - cd bin
          - ./start-conjur.sh
          - pipe: docker://cyberark/conjur-bitbucket-pipe:edge
            variables:
              CONJUR_URL: 'http://$BITBUCKET_DOCKER_HOST_INTERNAL:8888'
              CONJUR_ACCOUNT: 'conjur'
              CONJUR_SERVICE_ID: 'bitbucket'
              SECRETS: 'secret1,secret2'
        after-script:
          - docker-compose logs
        services:
          - docker
    - step:
        name: 'Load secrets'
        script:
          - ls -ltra $BITBUCKET_PIPE_SHARED_STORAGE_DIR
          - $BITBUCKET_PIPE_SHARED_STORAGE_DIR/load_secrets.sh
          - env | grep secret
          - ls -ltra $BITBUCKET_PIPE_SHARED_STORAGE_DIR
