image:
  name: atlassian/default-image:4

pipelines:
  default:
    - step:
        name: 'Test pipe'
        script:
          - cd bin
          - ./start-conjur.sh
          - docker-compose ps
          - pipe_api_key=$(docker-compose exec conjur conjurctl role retrieve-key conjur:host:pipe | tr -d '\r')
          - export CONJUR_API_KEY=$pipe_api_key
          - pipe: docker://cyberark/conjur-bitbucket-pipe:edge
            variables:
              CONJUR_URL: 'http://host.docker.internal:8888'
              CONJUR_ACCOUNT: 'conjur'
              SECRETS: 'secret1,secret2'
              CONJUR_AUTHN_LOGIN: 'host/pipe'
              CONJUR_API_KEY: $CONJUR_API_KEY
        services:
          - docker
        oidc: true
