image:
  name: atlassian/default-image:4

pipelines:
  default:
    - step:
        name: 'Unit tests'
        services:
          - docker
        script:
          - ./bin/test.sh

    - step:
        name: 'Run pipe with Conjur OSS'
        oidc: true
        script:
          - cd bin
          - ./start-conjur.sh
          # Note: This will use the latest docker image of the pipe, published by our internal CI.
          # This may not be the same as the code in this repository.
          - pipe: docker://cyberark/conjur-bitbucket-pipe:edge
            variables:
              CONJUR_URL: 'http://$BITBUCKET_DOCKER_HOST_INTERNAL:8888'
              SECRETS: 'bitbucket-pipelines/secret1,bitbucket-pipelines/secret2,bitbucket-pipelines/myvar'
              # These are the default values so they don't need to be set
              # CONJUR_ACCOUNT: 'conjur'
              # CONJUR_SERVICE_ID: 'bitbucket'
        after-script:
          - docker-compose logs
        services:
          - docker

    - step:
        name: 'Test secrets loading'
        script:
          - . /opt/atlassian/pipelines/agent/build/.bitbucket/pipelines/generated/pipeline/pipes/cyberark/conjur-bitbucket-pipe/load_secrets.sh
          - ./bin/e2e.sh
